Autoroute Off
Autotime On
Eqnetnames Off
NetMenus Off
BlkMenus Off
Autodrc On
Hilightwide Off
Updatehilight Off
Mouse COM1 B1 Select B2 Menu B3 Done
Cursor Arrow
Printer IBMGRAPH
Show Pips NoWorld Routed NoLocked NoProhibited NoRatsnest NoBidis NoSplitters NoDirectional Matrix NoPipconnections XLarge
Statusline Short
Snap Off
Router Fsadd 6
Router Eccadjust 8
Router Llcost 250
Router Llpipcount 20
Router Bidicost 0
Router Firstbidi 2
Router MBlaneswitch 1
